import os
def convertor (result):
    diffs = result[0]
    extra1info = result[1]
    extra2info = result[2]
    if os.path.isfile("result.csv"):
        os.remove("result.csv")
    with open("result.csv","w") as f:
        f.write("This file was generated by Netlist vs Netlist Comparation\n")
        f.write("Not Equal Subckts count is : " + str(len(diffs)) + "\n")
        f.write("Extra Subckts count in the first Netlist is : " + str(len(extra1info)) + "\n")
        f.write("Extra Subckts count in the second Netlist is : " + str(len(extra2info)) + "\n")
        for diff in diffs:
            for name in diff:
                f.write("---------------------------------------------------------------------------------------------------------------------------------------------------------\n")
                f.write("---------------------------------------------------------------------------------------------------------------------------------------------------------")
                f.write("\nSubckt "+name + "\n")
                portlist = diff[name][0]
                if portlist is not None:
                    f.write("Difference Beetwen port list:\n")
                    diffp = portlist[0]["diff"]
                    if diffp is not None:
                        f.write("Port difference beetwen port names\n")
                        for dp in diffp:
                            f.write(dp[0] + " : " + dp[1] + "," )
                        f.write("\n")
                    extra1p = portlist[1]["extra1"]
                    if extra1p is not None:
                        f.write("Extra port in the first Netlist:\n")
                        for dp in extra1p:
                            f.write(dp + "," )
                        f.write("\n")
                    extra2p = portlist[2]["extra2"]
                    if extra2p is not None:
                        f.write("Extra port in the second Netlist:\n")
                        for dp in extra2p:
                            f.write(dp + "," )
                        f.write("\n")
                #else:
                    #f.write("No difference beetwen port list:\n")
                #f.write("\n")



                paramlist = diff[name][1]
                if paramlist is not None:
                    f.write("Difference Beetwen parameter list:\n")
                    diffp = paramlist[0]["diff"]
                    if diffp is not None:
                        f.write("Parameter difference beetwen parameter names\n")
                        for dp in diffp:
                            f.write(dp[0] + " : " + dp[1] + "," )
                        f.write("\n")
                    extra1p = paramlist[1]["extra1"]
                    if extra1p is not None:
                        f.write("Extra parameter in the first Netlist:\n")
                        for dp in extra1p:
                            f.write(dp + "," )
                        f.write("\n")
                    extra2p = paramlist[2]["extra2"]
                    if extra2p is not None:
                        f.write("Extra parameter in the second Netlist:\n")
                        for dp in extra2p:
                            f.write(dp + "," )
                        f.write("\n")
                #else:
                    #f.write("No difference beetwen parameter list:\n")
                #f.write("\n")



                tranzDiff = diff[name][2]
                if tranzDiff is not None:
                    f.write("Difference beetwen Tranzistor list:\n")
                    diffT = tranzDiff[0]["TranzDiff"]
                    if diffT is not None:
                        f.write("name,drain,gate,source,bulk,type,nfin,lenght,m\n")
                        for t in diffT:
                            for s in t:
                                if s is None:
                                    f.write("pass,")
                                elif type(s) == str:
                                    f.write(s + ",")
                                else:
                                    f.write(s[0] + " : " + s[1] + ",")
                            f.write("\n")
                        f.write("\n")
                    extraT1 = tranzDiff[1]["Extra1"]
                    if extraT1 is not None:
                        f.write("Extra Tranzistors in the first Netlist:\n")
                        for t in extraT1:
                            f.write(t.getTName() + ",")
                        f.write("\n")
                    extraT2 = tranzDiff[2]["Extra2"]
                    if extraT2 is not None:
                        f.write("Extra Tranzistors in the second Netlist:\n")
                        for t in extraT2:
                            f.write(t.getTName() + ",")
                        f.write("\n")
                #else:
                    #f.write("No difference beetwen Tranzistor list:\n")
                #f.write("\n")







                instDiff = diff[name][3]
                if instDiff is not None:
                    f.write("Difference beetwen Instance list:\n")
                    diffI = instDiff[0]["diffInstaces"]
                    if diffI is not None:
                        f.write("Name,Type,Port List,Parameters\n")
                        for inf in diffI:
                            if inf is not None:
                                for i in inf:
                                    if i is None:
                                        f.write("pass,")
                                    elif type(i) == str:
                                        f.write(i + ",")
                                    elif type(i) == list:
                                        if len(i) == 2:
                                            f.write(i[0] + " : " + i[1] + ",")
                                        else:
                                            diffport = i[0]["diff"]
                                            if diffport is not None:
                                                for p in diffport:
                                                    f.write(p[0] + ":" + p[1] + ";   ")
                                            extrap1 = i[1]["extra1"]
                                            if extrap1 is not None:
                                                f.write("       Extra nets in the first netlist:")
                                                for p in extrap1:
                                                    f.write(p + ";")
                                            extrap2 = i[2]["extra2"]
                                            if extrap2 is not None:
                                                f.write("       Extra nets in the second netlist:")
                                                for p in extrap2:
                                                    f.write(p + ";")
                                        f.write(",")
                                f.write("\n")
                        f.write("\n")
                    extra1 = instDiff[1]["ExtraInstances1"]
                    if extra1 is not None:
                        f.write("Extra Instances in the first Netlist\n")
                        for i1 in extra1:
                            f.write("Name: " + i1.getName() + "    Type: " + i1.getType() + ",")
                        f.write("\n")
                    extra2 = instDiff[2]["ExtraInstances2"]
                    if extra2 is not None:
                        f.write("Extra Instances in the second Netlist\n")
                        for i2 in extra2:
                            f.write("Name: " + i2.getName() + "    Type: " + i2.getType() + ",")
                        f.write("\n")
                #else:
                    #f.write("No difference beetwen Instance list:\n")
                #f.write("\n")

        if extra1info is not None:
            f.write("Extra Subckt in the First Netlist:\n")
            for ex1i in extra1info:
                f.write(ex1i.getName() + "\n")
            f.write("\n")
            #f.write("\n")
        if extra2info is not None:
            f.write("Extra Subckt in the Second Netlist:\n")
            for ex2i in extra2info:
                f.write(ex2i.getName() + "\n")
            #f.write("\n")

